openapi: 3.1.0
info:
  title: api
  version: '1.0'
  summary: go-clean-architecture
servers:
  - url: 'http://localhost:3000'
paths:
  /:
    get:
      summary: Greeting
      tags: []
      operationId: ''
      description: Get greeting.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  greeting:
                    type: string
components:
  schemas: {}
